stages:
  - build
  - push

build_ce7:
  stage: build
  image: git.zswap.net:5050/nathans/centos:7
  script:
    - yum -y install python3-pip
    - pip3 install --upgrade pip
    - pip3 install build twine
    - python3 -m build
  artifacts:
    paths:
      - dist
    expire_in: 7d

build_ce8:
  stage: build
  image: git.zswap.net:5050/nathans/centos:8
  script:
    - dnf -y install python3-pip
    - pip3 install --upgrade pip
    - pip3 install build twine
    - python3 -m build
  artifacts:
    paths:
      - dist
    expire_in: 7d
  
build_deb10:
  stage: build
  image: git.zswap.net:5050/nathans/debian:10
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install --upgrade pip
    - pip3 install build twine
    - python3 -m build
  artifacts:
    paths:
      - dist
    expire_in: 7d

build_deb11:
  stage: build
  image: git.zswap.net:5050/nathans/debian:11
  script:
    - apt-get update && apt-get install -y python3-pip python3-venv
    - pip3 install --upgrade pip
    - pip3 install build twine
    - python3 -m build
  artifacts:
    paths:
      - dist
    expire_in: 7d

push:
  stage: push
  image: git.zswap.net:5050/nathans/centos:8
  script:
    - dnf -y install python3-pip
    - pip3 install --upgrade pip
    - pip3 install twine
    - python3 -m twine upload --repository testpypi dist/* --username __token__ --password $PYPI_API_KEY