---
stages:
  - build
  - test
  - push


build:
  stage: build
  image: python:3
  script:
    - pip3 install --upgrade pip
    - pip3 install build twine
    - python3 -m build
  artifacts:
    paths:
      - dist
    expire_in: 7d
  

test:
  stage: test
  image: python:3
  script:
    - pip3 install --upgrade pip
    - pip3 install .
    - pip3 install pytest
    - pytest


push:
  stage: push
  when: on_success
  image: python:3
  script:
    - pip3 install --upgrade pip
    - pip3 install twine
    - python3 -m twine upload --repository testpypi dist/* --username __token__ --password $PYPI_API_KEY